name: .NET Core Test Otomasyonu

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Getir
      uses: actions/checkout@v4

    - name: .NET SDK Kur
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x # Kendi projenin versiyonuyla (6.0, 7.0 vb.) değiştir

    - name: Paketleri Yukle
      run: dotnet restore

    - name: Projeyi Derle
      run: dotnet build --no-restore

    - name: Testleri Kos
      run: dotnet test --no-build --verbosity normal